<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <script src="./promise.js"></script>
  </head>
  <body>
    <script>
      let p = new Promise((resolve, reject) => {
        setTimeout(() => {
          // reject('error')
          resolve('ok')
        }, 1000)
      })
      /**
       * catch的异常穿透测试
       */
      p.then()
        .then((value) => {
          console.log(222)
          throw '???'
        })
        .then((value) => {
          console.log(333)
        })
        .catch((err) => {
          console.log(err)
        })

      /**
       *
       * catch的基本实现测试
       */
      // let res = p.catch((err) => {
      //   console.log(err)
      //   // throw '1'
      //   // return 1
      //   // return new Promise((resolve, reject) => {
      //   //   reject('111')
      //   // })
      // })
      // console.log(res)
    </script>
  </body>
</html>
